"use client";
import {useState} from 'react';import {api} from '../../lib/api';
const PROGRAMS=['B.Tech','B.E.','BBA','B.Com','B.Des','B.Sc','M.Sc','BCA','MCA','M.Tech','MBA','Diploma','Other'];
const BRANCHES=['CSE','IT','ECE','EEE','Mechanical','Civil','AI & ML','Data Science','Cyber Security','Other'];
const PROOFS=['College Allotment Order','No Objection Certificate (NOC)','Internship Permission / Recommendation Letter','Bonafide Certificate with internship permission','Other'];
export default function Register(){
 const [f,setF]=useState({email:'',password:'',fullName:'',mobile:'',dob:'',address:'',college:'',collegeOther:'',university:'',program:'',programOther:'',branch:'',branchOther:'',yearSemester:'',rollNumber:'',preferredDomains:'',preferredBatch:'',modePreference:'',skillsTools:'',resumePortfolioUrl:'',proofType:'',issuingAuthority:'',referenceNumber:'',issueDate:'',approvedFrom:'',approvedTo:'',coordinatorName:'',coordinatorDesignation:'',coordinatorEmail:'',coordinatorPhone:'',consentGenuine:false,consentStorage:false}),[files,setFiles]=useState([]),[photo,setPhoto]=useState(null),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 async function submit(e){e.preventDefault();setErr('');setMsg('');try{if(!files.length)throw new Error('Please upload the college permission proof.');if(files.length>2)throw new Error('Maximum 2 proof files are allowed.');const prefs=f.preferredDomains.split(',').map(x=>x.trim()).filter(Boolean);if(prefs.length>3)throw new Error('Choose up to 3 preferred domains only.');const body=new FormData();Object.entries(f).forEach(([k,v])=>body.append(k,String(v)));body.set('preferredDomains',JSON.stringify(prefs));files.forEach(x=>body.append('proofFiles',x));if(photo)body.append('photo',photo);await api('/auth/register',{method:'POST',body});setMsg('Application received. Your college permission proof is pending Admin verification. Login remains disabled until verification and Admin approval.')}catch(x){setErr(x.message)}}
 return <main className="wrap"><div className="card" style={{maxWidth:760,margin:'30px auto'}}><h1>Intern Application</h1>{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}<form onSubmit={submit}>
 <h3>Personal Details</h3><label>Full Name (as in college records)</label><input className="input" value={f.fullName} onChange={e=>set('fullName',e.target.value)} required/><label>Email</label><input className="input" type="email" value={f.email} onChange={e=>set('email',e.target.value)} required/><label>Mobile</label><input className="input" value={f.mobile} onChange={e=>set('mobile',e.target.value)} required/><label>Date of Birth</label><input className="input" type="date" value={f.dob} onChange={e=>set('dob',e.target.value)} required/><label>Address</label><textarea className="input" value={f.address} onChange={e=>set('address',e.target.value)} required/><label>Photo (optional)</label><input className="input" type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" onChange={e=>setPhoto(e.target.files?.[0]||null)}/>
 <h3>Academic Details</h3><label>College</label><input className="input" value={f.college} onChange={e=>set('college',e.target.value)} required placeholder="Enter/select college"/><label>University</label><input className="input" value={f.university} onChange={e=>set('university',e.target.value)} required/>
 <label>Program</label><select className="input" value={f.program} onChange={e=>{set('program',e.target.value);if(e.target.value!=='Other')set('programOther','')}} required><option value="">Select program</option>{PROGRAMS.map(x=><option key={x}>{x}</option>)}</select>{f.program==='Other'&&<><label>Enter Program Name</label><input className="input" value={f.programOther} onChange={e=>set('programOther',e.target.value)} required/></>}
 <label>Branch / Department</label><select className="input" value={f.branch} onChange={e=>{set('branch',e.target.value);if(e.target.value!=='Other')set('branchOther','')}} required><option value="">Select branch / department</option>{BRANCHES.map(x=><option key={x}>{x}</option>)}</select>{f.branch==='Other'&&<><label>Enter Branch / Department</label><input className="input" value={f.branchOther} onChange={e=>set('branchOther',e.target.value)} required/></>}
 <label>Year / Semester</label><input className="input" value={f.yearSemester} onChange={e=>set('yearSemester',e.target.value)} required/><label>Roll / Registration Number</label><input className="input" value={f.rollNumber} onChange={e=>set('rollNumber',e.target.value)} required/>
 <h3>Internship Preference</h3><label>Preferred Domains (up to 3, in preference order)</label><input className="input" value={f.preferredDomains} onChange={e=>set('preferredDomains',e.target.value)} placeholder="Example: Data Analytics, AI/ML, Full Stack"/><label>Preferred Batch / Start Month</label><input className="input" value={f.preferredBatch} onChange={e=>set('preferredBatch',e.target.value)}/><label>Mode Preference</label><select className="input" value={f.modePreference} onChange={e=>set('modePreference',e.target.value)}><option value="">Select if offered</option><option value="ONSITE">On-site</option><option value="REMOTE">Remote</option></select><label>Skills & Tools Known</label><textarea className="input" value={f.skillsTools} onChange={e=>set('skillsTools',e.target.value)}/><label>Resume / Portfolio Link (optional)</label><input className="input" type="url" value={f.resumePortfolioUrl} onChange={e=>set('resumePortfolioUrl',e.target.value)}/>
 <h3>College Permission Proof</h3><label>Proof Type</label><select className="input" value={f.proofType} onChange={e=>set('proofType',e.target.value)} required><option value="">Select proof type</option>{PROOFS.map(x=><option key={x}>{x}</option>)}</select><label>Issuing Authority / Signatory Designation</label><input className="input" value={f.issuingAuthority} onChange={e=>set('issuingAuthority',e.target.value)} required placeholder="Principal / HoD / TPO / Dean"/><label>Letter / Reference Number</label><input className="input" value={f.referenceNumber} onChange={e=>set('referenceNumber',e.target.value)} required/><label>Issue Date</label><input className="input" type="date" value={f.issueDate} max={new Date().toISOString().slice(0,10)} onChange={e=>set('issueDate',e.target.value)} required/><label>College-approved Internship From</label><input className="input" type="date" value={f.approvedFrom} onChange={e=>set('approvedFrom',e.target.value)} required/><label>College-approved Internship To</label><input className="input" type="date" value={f.approvedTo} min={f.approvedFrom||undefined} onChange={e=>set('approvedTo',e.target.value)} required/>
 <h4>Faculty Coordinator</h4><label>Name</label><input className="input" value={f.coordinatorName} onChange={e=>set('coordinatorName',e.target.value)} required/><label>Designation</label><input className="input" value={f.coordinatorDesignation} onChange={e=>set('coordinatorDesignation',e.target.value)} required/><label>Official Email</label><input className="input" type="email" value={f.coordinatorEmail} onChange={e=>set('coordinatorEmail',e.target.value)} required/><label>Phone</label><input className="input" value={f.coordinatorPhone} onChange={e=>set('coordinatorPhone',e.target.value)} required/><label>Upload Proof (PDF/JPG/PNG, max 5 MB each, up to 2 files)</label><input className="input" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,2))} required/>
 <label>Password (10+ characters)</label><input className="input" type="password" minLength="10" onChange={e=>set('password',e.target.value)} required/><label><input type="checkbox" checked={f.consentGenuine} onChange={e=>set('consentGenuine',e.target.checked)} required/> I confirm the uploaded document is genuine and issued by my college.</label><br/><label><input type="checkbox" checked={f.consentStorage} onChange={e=>set('consentStorage',e.target.checked)} required/> I consent to GAINT storing and verifying the document for internship administration.</label><p><button className="btn">Submit Application</button></p>
 </form></div></main>}
