import {Router} from 'express';import fs from 'fs';import path from 'path';import {q,tx} from '../config/db.js';import {auth,permit} from '../middleware/auth.js';import {audit} from '../utils/audit.js';
const r=Router(); r.use(auth,permit('ADMIN','SUPER_ADMIN'));
r.get('/dashboard',async(req,res)=>{const sql=`SELECT (SELECT count(*) FROM users WHERE role='INTERN') interns,(SELECT count(*) FROM college_proofs WHERE status IN ('UPLOADED','UNDER_REVIEW')) proofs_pending,(SELECT count(*) FROM users WHERE role='INTERN' AND status='PENDING_APPROVAL') approvals_pending,(SELECT count(*) FROM face_enrollments WHERE status='PENDING_ADMIN_APPROVAL') faces_pending,(SELECT count(*) FROM task_submissions WHERE status='SUBMITTED') task_evaluations_pending,(SELECT count(*) FROM attendance_exceptions WHERE status NOT IN ('CLOSED','REJECTED')) attendance_exceptions`;res.json((await q(sql)).rows[0])});
r.get('/proofs',async(req,res)=>res.json((await q(`SELECT cp.*,ip.full_name,ip.roll_number,ip.program,ip.branch,ip.user_id,c.name college_name FROM college_proofs cp JOIN intern_profiles ip ON ip.id=cp.intern_id LEFT JOIN colleges c ON c.id=ip.college_id ORDER BY cp.created_at DESC`)).rows));
r.post('/proofs/:id/verify',async(req,res)=>{const {outcome,reason,checklist={}}=req.body;if(!['VERIFIED','REUPLOAD_REQUESTED','REJECTED','OVERRIDE'].includes(outcome))return res.status(400).json({error:'Invalid outcome'});if(outcome!=='VERIFIED'&&!reason)return res.status(400).json({error:'Reason required'});const p=(await q('UPDATE college_proofs SET status=$1,reason=$2 WHERE id=$3 RETURNING *',[outcome,reason||null,req.params.id])).rows[0];await q('INSERT INTO proof_verifications(proof_id,actor_id,outcome,checklist,reason) VALUES($1,$2,$3,$4,$5)',[p.id,req.user.id,outcome,checklist,reason]);await audit(req,'PROOF_'+outcome,'college_proof',p.id,null,p);res.json(p)});
r.post('/interns/:userId/approve',async(req,res)=>{const proof=(await q(`SELECT cp.status FROM college_proofs cp JOIN intern_profiles ip ON ip.id=cp.intern_id WHERE ip.user_id=$1 ORDER BY cp.created_at DESC LIMIT 1`,[req.params.userId])).rows[0];if(proof?.status!=='VERIFIED'&&req.user.role!=='SUPER_ADMIN')return res.status(409).json({error:'Verified college proof required'});if(proof?.status!=='VERIFIED'&&!req.body.overrideReason)return res.status(400).json({error:'Super Admin override reason required'});const u=(await q("UPDATE users SET status='ACTIVE',is_active=true WHERE id=$1 AND role='INTERN' RETURNING id,email,status",[req.params.userId])).rows[0];await audit(req,'ACCOUNT_APPROVED','user',req.params.userId,null,{...u,overrideReason:req.body.overrideReason});res.json(u)});
for(const [path,table] of Object.entries({colleges:'colleges',domains:'domains',batches:'batches',projects:'projects',questions:'question_bank',assessments:'assessments',tasks:'weekly_tasks',groups:'groups'})){r.get('/'+path,async(req,res)=>res.json((await q(`SELECT * FROM ${table} ORDER BY 1 DESC`)).rows));}
r.post('/domains',async(req,res)=>{const {name,code,category,description,defaultCapacity=25,allowedDeliverables=[]}=req.body;const x=(await q('INSERT INTO domains(name,code,category,description,default_capacity,allowed_deliverables) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,code,category,description,defaultCapacity,allowedDeliverables])).rows[0];await audit(req,'DOMAIN_CREATE','domain',x.id,null,x);res.status(201).json(x)});
r.post('/colleges',async(req,res)=>{const x=(await q('INSERT INTO colleges(name,university) VALUES($1,$2) RETURNING *',[req.body.name,req.body.university])).rows[0];res.status(201).json(x)});
r.post('/batches',async(req,res)=>{const b=req.body;const x=(await q('INSERT INTO batches(college_id,name,code,start_date,end_date,mode,task_release_rule,review_rule,min_attendance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[b.collegeId,b.name,b.code,b.startDate,b.endDate,b.mode||'ONSITE',b.taskReleaseRule||{},b.reviewRule||{},b.minAttendance||75])).rows[0];res.status(201).json(x)});
r.post('/allocate',async(req,res)=>{const {batchId,internId}=req.body;const x=(await q(`INSERT INTO batch_allocations(batch_id,intern_id,intern_start,intern_end,date_mismatch) SELECT $1,$2,b.start_date,b.end_date,CASE WHEN cp.approved_from>b.start_date OR cp.approved_to<b.end_date THEN true ELSE false END FROM batches b LEFT JOIN college_proofs cp ON cp.intern_id=$2 AND cp.status='VERIFIED' WHERE b.id=$1 RETURNING *`,[batchId,internId])).rows[0];res.status(201).json(x)});
r.post('/offer-letters',async(req,res)=>{const {allocationId,fromDate,toDate,issueAt,templateId}=req.body;const x=(await q(`INSERT INTO offer_letters(allocation_id,student_name_snapshot,college_snapshot,batch_snapshot,from_date,to_date,duration_text,issue_at,template_id,template_version,reference_number,status,issued_by) SELECT ba.id,ip.full_name,c.name,b.name,$2,$3,($3::date-$2::date+1)||' days',$4,$5,olt.version,'GAINT-'||to_char(now(),'YYYY')||'-'||upper(substr(md5(random()::text),1,8)),'ISSUED',$6 FROM batch_allocations ba JOIN intern_profiles ip ON ip.id=ba.intern_id JOIN batches b ON b.id=ba.batch_id LEFT JOIN colleges c ON c.id=b.college_id LEFT JOIN offer_letter_templates olt ON olt.id=$5 WHERE ba.id=$1 RETURNING *`,[allocationId,fromDate,toDate,issueAt,templateId,req.user.id])).rows[0];if(!x)return res.status(404).json({error:'Allocation not found'});await q('INSERT INTO offer_letter_versions(offer_letter_id,version,snapshot) VALUES($1,1,$2)',[x.id,x]);await audit(req,'OFFER_ISSUED','offer_letter',x.id,null,x);res.status(201).json(x)});
r.post('/face/:id/decision',async(req,res)=>{const {status,reason}=req.body;if(!['APPROVED','REJECTED','REENROLLMENT_REQUIRED'].includes(status))return res.status(400).json({error:'Invalid status'});const x=(await q('UPDATE face_enrollments SET status=$1,decision_reason=$2,approved_by=$3,approved_at=now() WHERE id=$4 RETURNING *',[status,reason,req.user.id,req.params.id])).rows[0];await audit(req,'FACE_'+status,'face_enrollment',x.id,null,x);res.json(x)});
r.post('/domain-confirm',async(req,res)=>{const {internId,batchId,domainId,recommendations=[],preferences=[]}=req.body;const x=(await q('INSERT INTO domain_decisions(intern_id,batch_id,preferences,recommendations,confirmed_domain_id,confirmed_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[internId,batchId,preferences,recommendations,domainId,req.user.id])).rows[0];await q('UPDATE intern_profiles SET final_domain_id=$1 WHERE id=$2',[domainId,internId]);res.status(201).json(x)});
r.post('/groups/:id/approve',async(req,res)=>res.json((await q("UPDATE groups SET status='ACTIVE' WHERE id=$1 RETURNING *",[req.params.id])).rows[0]));
r.post('/attendance-exceptions/:id/decision',async(req,res)=>{const {status,reason}=req.body;const x=(await q('UPDATE attendance_exceptions SET status=$1,reason=COALESCE($2,reason),decided_by=$3,decided_at=now() WHERE id=$4 RETURNING *',[status,reason,req.user.id,req.params.id])).rows[0];await audit(req,'ATTENDANCE_EXCEPTION_'+status,'attendance_exception',x.id,null,x);res.json(x)});
r.get('/proofs/:id/file',async(req,res)=>{const p=(await q('SELECT file_path FROM college_proofs WHERE id=$1',[req.params.id])).rows[0];if(!p?.file_path)return res.status(404).json({error:'Proof file not found'});const file=path.resolve(p.file_path);if(!fs.existsSync(file))return res.status(404).json({error:'Proof file is missing from storage'});res.sendFile(file)});
r.get('/audit',async(req,res)=>res.json((await q('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 500')).rows)); export default r;
