import {Router} from 'express';import fs from 'fs';import path from 'path';import {q,tx} from '../config/db.js';import {auth,permit} from '../middleware/auth.js';import {audit} from '../utils/audit.js';
const r=Router(); r.use(auth,permit('ADMIN','SUPER_ADMIN'));
r.get('/dashboard',async(req,res)=>{const sql=`SELECT (SELECT count(*) FROM users WHERE role='INTERN') interns,(SELECT count(*) FROM college_proofs WHERE status IN ('UPLOADED','UNDER_REVIEW')) proofs_pending,(SELECT count(*) FROM users WHERE role='INTERN' AND status='PENDING_APPROVAL') approvals_pending,(SELECT count(*) FROM face_enrollments WHERE status='PENDING_ADMIN_APPROVAL') faces_pending,(SELECT count(*) FROM task_submissions WHERE status='SUBMITTED') task_evaluations_pending,(SELECT count(*) FROM attendance_exceptions WHERE status NOT IN ('CLOSED','REJECTED')) attendance_exceptions`;res.json((await q(sql)).rows[0])});
r.get('/proofs',async(req,res)=>res.json((await q(`SELECT cp.*,ip.full_name,ip.roll_number,ip.program,ip.branch,ip.user_id,ip.university,ip.year_semester,ip.mobile,c.name college_name,u.email,u.status account_status,u.is_active,cc.name coordinator_name,cc.designation coordinator_designation,cc.email coordinator_email,cc.phone coordinator_phone,
 EXISTS(SELECT 1 FROM college_proofs d WHERE d.id<>cp.id AND lower(d.reference_number)=lower(cp.reference_number) AND d.status<>'REJECTED') duplicate_reference,
 EXISTS(SELECT 1 FROM college_proofs d WHERE d.id<>cp.id AND d.file_hash=cp.file_hash AND d.status<>'REJECTED') duplicate_file,
 ba.intern_start allocated_from,ba.intern_end allocated_to,
 CASE WHEN ba.id IS NOT NULL AND (cp.approved_from>ba.intern_start OR cp.approved_to<ba.intern_end) THEN true ELSE false END date_mismatch,
 pv.checklist last_checklist,pv.outcome last_outcome,pv.reason last_verification_reason,pv.created_at last_verified_at
 FROM college_proofs cp JOIN intern_profiles ip ON ip.id=cp.intern_id JOIN users u ON u.id=ip.user_id LEFT JOIN colleges c ON c.id=ip.college_id LEFT JOIN college_coordinators cc ON cc.id=cp.coordinator_id
 LEFT JOIN LATERAL (SELECT * FROM batch_allocations x WHERE x.intern_id=ip.id ORDER BY x.intern_start DESC NULLS LAST LIMIT 1) ba ON true
 LEFT JOIN LATERAL (SELECT * FROM proof_verifications x WHERE x.proof_id=cp.id ORDER BY x.created_at DESC LIMIT 1) pv ON true
 ORDER BY cp.created_at DESC`)).rows));
r.post('/proofs/:id/verify',async(req,res)=>{const {outcome,reason,checklist={}}=req.body;if(!['VERIFIED','REUPLOAD_REQUESTED','REJECTED','OVERRIDE'].includes(outcome))return res.status(400).json({error:'Invalid outcome'});if(outcome!=='VERIFIED'&&!String(reason||'').trim())return res.status(400).json({error:'Reason required for re-upload, rejection or override'});
 const proof=(await q(`SELECT cp.*,ip.full_name,ip.roll_number,c.name college_name,ba.intern_start,ba.intern_end,
 EXISTS(SELECT 1 FROM college_proofs d WHERE d.id<>cp.id AND lower(d.reference_number)=lower(cp.reference_number) AND d.status<>'REJECTED') duplicate_reference,
 EXISTS(SELECT 1 FROM college_proofs d WHERE d.id<>cp.id AND d.file_hash=cp.file_hash AND d.status<>'REJECTED') duplicate_file
 FROM college_proofs cp JOIN intern_profiles ip ON ip.id=cp.intern_id LEFT JOIN colleges c ON c.id=ip.college_id LEFT JOIN LATERAL (SELECT * FROM batch_allocations x WHERE x.intern_id=ip.id ORDER BY x.intern_start DESC NULLS LAST LIMIT 1) ba ON true WHERE cp.id=$1`,[req.params.id])).rows[0];
 if(!proof)return res.status(404).json({error:'Proof not found'});
 const required=['nameMatch','rollMatch','collegeMatch','datesValid','signatureSeal','referenceMatch','duplicateChecked'];const missing=required.filter(k=>checklist[k]!==true);
 const dateMismatch=!!(proof.intern_start&&proof.intern_end&&(new Date(proof.approved_from)>new Date(proof.intern_start)||new Date(proof.approved_to)<new Date(proof.intern_end)));
 if(outcome==='VERIFIED'&&missing.length)return res.status(400).json({error:'Complete every verification checklist item before verifying',missing});
 if(outcome==='VERIFIED'&&(proof.duplicate_reference||proof.duplicate_file))return res.status(409).json({error:'Duplicate reference/file detected. Resolve the duplicate before verification.'});
 if(outcome==='VERIFIED'&&dateMismatch)return res.status(409).json({error:'College-approved dates do not cover the allocated internship dates.'});
 const p=await tx(async c=>{const updated=(await c.query('UPDATE college_proofs SET status=$1,reason=$2 WHERE id=$3 RETURNING *',[outcome,reason||null,req.params.id])).rows[0];await c.query('INSERT INTO proof_verifications(proof_id,actor_id,outcome,checklist,reason) VALUES($1,$2,$3,$4,$5)',[updated.id,req.user.id,outcome,checklist,reason||null]);const userStatus=outcome==='VERIFIED'?'PENDING_APPROVAL':outcome==='REUPLOAD_REQUESTED'?'PROOF_REUPLOAD_REQUIRED':outcome==='REJECTED'?'PROOF_REJECTED':'PROOF_OVERRIDE';await c.query("UPDATE users u SET status=$1,is_active=CASE WHEN $2='REJECTED' THEN false ELSE is_active END FROM intern_profiles ip WHERE ip.user_id=u.id AND ip.id=$3",[userStatus,outcome,updated.intern_id]);return updated});await audit(req,'PROOF_'+outcome,'college_proof',p.id,proof,{...p,checklist,dateMismatch});res.json({...p,dateMismatch})});
r.post('/interns/:userId/approve',async(req,res)=>{const proof=(await q(`SELECT cp.status FROM college_proofs cp JOIN intern_profiles ip ON ip.id=cp.intern_id WHERE ip.user_id=$1 ORDER BY cp.created_at DESC LIMIT 1`,[req.params.userId])).rows[0];if(proof?.status!=='VERIFIED'&&req.user.role!=='SUPER_ADMIN')return res.status(409).json({error:'Verified college proof required'});if(proof?.status!=='VERIFIED'&&!req.body.overrideReason)return res.status(400).json({error:'Super Admin override reason required'});const u=(await q("UPDATE users SET status='ACTIVE',is_active=true WHERE id=$1 AND role='INTERN' RETURNING id,email,status",[req.params.userId])).rows[0];await audit(req,'ACCOUNT_APPROVED','user',req.params.userId,null,{...u,overrideReason:req.body.overrideReason});res.json(u)});
for(const [path,table] of Object.entries({colleges:'colleges',domains:'domains',batches:'batches',projects:'projects',questions:'question_bank',assessments:'assessments',tasks:'weekly_tasks',groups:'groups'})){r.get('/'+path,async(req,res)=>res.json((await q(`SELECT * FROM ${table} ORDER BY 1 DESC`)).rows));}
r.post('/domains',async(req,res)=>{const {name,code,category,description,defaultCapacity=25,allowedDeliverables=[]}=req.body;const x=(await q('INSERT INTO domains(name,code,category,description,default_capacity,allowed_deliverables) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,code,category,description,defaultCapacity,allowedDeliverables])).rows[0];await audit(req,'DOMAIN_CREATE','domain',x.id,null,x);res.status(201).json(x)});
r.post('/colleges',async(req,res)=>{const name=String(req.body.name||'').trim(),university=String(req.body.university||'').trim();if(!name)return res.status(400).json({error:'College name is required'});try{const x=(await q('INSERT INTO colleges(name,university,active) VALUES($1,$2,true) RETURNING *',[name,university||null])).rows[0];await audit(req,'COLLEGE_CREATE','college',x.id,null,x);res.status(201).json(x)}catch(e){if(e.code==='23505')return res.status(409).json({error:'College already exists'});throw e}});
r.patch('/colleges/:id',async(req,res)=>{const before=(await q('SELECT * FROM colleges WHERE id=$1',[req.params.id])).rows[0];if(!before)return res.status(404).json({error:'College not found'});const name=String(req.body.name??before.name).trim(),university=String(req.body.university??before.university??'').trim(),active=req.body.active===undefined?before.active:!!req.body.active;try{const x=(await q('UPDATE colleges SET name=$1,university=$2,active=$3 WHERE id=$4 RETURNING *',[name,university||null,active,req.params.id])).rows[0];await audit(req,'COLLEGE_UPDATE','college',x.id,before,x);res.json(x)}catch(e){if(e.code==='23505')return res.status(409).json({error:'College name already exists'});throw e}});
r.post('/batches',async(req,res)=>{const b=req.body;const x=(await q('INSERT INTO batches(college_id,name,code,start_date,end_date,mode,task_release_rule,review_rule,min_attendance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[b.collegeId,b.name,b.code,b.startDate,b.endDate,b.mode||'ONSITE',b.taskReleaseRule||{},b.reviewRule||{},b.minAttendance||75])).rows[0];res.status(201).json(x)});
r.post('/allocate',async(req,res)=>{const {batchId,internId,internStart,internEnd,overrideReason}=req.body;const info=(await q(`SELECT b.*,ip.full_name,ip.college_id intern_college,cp.id proof_id,cp.approved_from,cp.approved_to,cp.reference_number FROM batches b JOIN intern_profiles ip ON ip.id=$2 LEFT JOIN LATERAL (SELECT * FROM college_proofs p WHERE p.intern_id=ip.id AND p.status='VERIFIED' ORDER BY p.created_at DESC LIMIT 1) cp ON true WHERE b.id=$1`,[batchId,internId])).rows[0];if(!info)return res.status(404).json({error:'Batch or intern not found'});if(!info.proof_id)return res.status(409).json({error:'Verified college permission proof is required before duration allocation'});if(info.college_id&&info.intern_college&&info.college_id!==info.intern_college)return res.status(409).json({error:'Intern college does not match the selected batch college'});const start=internStart||info.start_date,end=internEnd||info.end_date;if(new Date(end)<new Date(start))return res.status(400).json({error:'Internship end date cannot be before start date'});if(new Date(start)<new Date(info.start_date)||new Date(end)>new Date(info.end_date))return res.status(400).json({error:'Internship dates must stay within the selected batch dates'});const mismatch=new Date(info.approved_from)>new Date(start)||new Date(info.approved_to)<new Date(end);if(mismatch&&!String(overrideReason||'').trim())return res.status(409).json({error:'Selected duration is outside the college-approved period. Provide an Admin override reason or correct the dates.'});const before=(await q('SELECT * FROM batch_allocations WHERE batch_id=$1 AND intern_id=$2',[batchId,internId])).rows[0]||null;const x=(await q(`INSERT INTO batch_allocations(batch_id,intern_id,status,intern_start,intern_end,date_mismatch,override_reason) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(batch_id,intern_id) DO UPDATE SET intern_start=EXCLUDED.intern_start,intern_end=EXCLUDED.intern_end,date_mismatch=EXCLUDED.date_mismatch,override_reason=EXCLUDED.override_reason,status=EXCLUDED.status RETURNING *`,[batchId,internId,mismatch?'ALLOTTED_WITH_OVERRIDE':'ALLOTMENT_VERIFIED',start,end,mismatch,overrideReason||null])).rows[0];await q('INSERT INTO allotment_verifications(allocation_id,actor_id,status,reason) VALUES($1,$2,$3,$4)',[x.id,req.user.id,mismatch?'OVERRIDDEN':'VERIFIED',overrideReason||null]);await audit(req,before?'ALLOCATION_UPDATE':'ALLOCATION_CREATE','batch_allocation',x.id,before,{...x,proofReference:info.reference_number});res.status(before?200:201).json({...x,proofApprovedFrom:info.approved_from,proofApprovedTo:info.approved_to})});
r.get('/allocations',async(req,res)=>res.json((await q(`SELECT ba.*,ip.full_name,ip.roll_number,c.name college_name,b.name batch_name,b.code batch_code,b.start_date batch_start,b.end_date batch_end,cp.approved_from proof_from,cp.approved_to proof_to,cp.reference_number proof_reference,av.status verification_status,av.reason verification_reason,av.created_at verified_at FROM batch_allocations ba JOIN intern_profiles ip ON ip.id=ba.intern_id JOIN batches b ON b.id=ba.batch_id LEFT JOIN colleges c ON c.id=ip.college_id LEFT JOIN LATERAL (SELECT * FROM college_proofs p WHERE p.intern_id=ip.id AND p.status='VERIFIED' ORDER BY p.created_at DESC LIMIT 1) cp ON true LEFT JOIN LATERAL (SELECT * FROM allotment_verifications x WHERE x.allocation_id=ba.id ORDER BY x.created_at DESC LIMIT 1) av ON true ORDER BY ba.intern_start DESC`)).rows));
r.post('/offer-letters',async(req,res)=>{const {allocationId,fromDate,toDate,issueAt,templateId}=req.body;const x=(await q(`INSERT INTO offer_letters(allocation_id,student_name_snapshot,college_snapshot,batch_snapshot,from_date,to_date,duration_text,issue_at,template_id,template_version,reference_number,status,issued_by) SELECT ba.id,ip.full_name,c.name,b.name,$2,$3,($3::date-$2::date+1)||' days',$4,$5,olt.version,'GAINT-'||to_char(now(),'YYYY')||'-'||upper(substr(md5(random()::text),1,8)),'ISSUED',$6 FROM batch_allocations ba JOIN intern_profiles ip ON ip.id=ba.intern_id JOIN batches b ON b.id=ba.batch_id LEFT JOIN colleges c ON c.id=b.college_id LEFT JOIN offer_letter_templates olt ON olt.id=$5 WHERE ba.id=$1 RETURNING *`,[allocationId,fromDate,toDate,issueAt,templateId,req.user.id])).rows[0];if(!x)return res.status(404).json({error:'Allocation not found'});await q('INSERT INTO offer_letter_versions(offer_letter_id,version,snapshot) VALUES($1,1,$2)',[x.id,x]);await audit(req,'OFFER_ISSUED','offer_letter',x.id,null,x);res.status(201).json(x)});
r.post('/face/:id/decision',async(req,res)=>{const {status,reason}=req.body;if(!['APPROVED','REJECTED','REENROLLMENT_REQUIRED'].includes(status))return res.status(400).json({error:'Invalid status'});const x=(await q('UPDATE face_enrollments SET status=$1,decision_reason=$2,approved_by=$3,approved_at=now() WHERE id=$4 RETURNING *',[status,reason,req.user.id,req.params.id])).rows[0];await audit(req,'FACE_'+status,'face_enrollment',x.id,null,x);res.json(x)});
r.post('/domain-confirm',async(req,res)=>{const {internId,batchId,domainId,recommendations=[],preferences=[]}=req.body;const x=(await q('INSERT INTO domain_decisions(intern_id,batch_id,preferences,recommendations,confirmed_domain_id,confirmed_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[internId,batchId,preferences,recommendations,domainId,req.user.id])).rows[0];await q('UPDATE intern_profiles SET final_domain_id=$1 WHERE id=$2',[domainId,internId]);res.status(201).json(x)});
r.post('/groups/:id/approve',async(req,res)=>res.json((await q("UPDATE groups SET status='ACTIVE' WHERE id=$1 RETURNING *",[req.params.id])).rows[0]));
r.post('/attendance-exceptions/:id/decision',async(req,res)=>{const {status,reason}=req.body;const x=(await q('UPDATE attendance_exceptions SET status=$1,reason=COALESCE($2,reason),decided_by=$3,decided_at=now() WHERE id=$4 RETURNING *',[status,reason,req.user.id,req.params.id])).rows[0];await audit(req,'ATTENDANCE_EXCEPTION_'+status,'attendance_exception',x.id,null,x);res.json(x)});
r.get('/proofs/:id/file',async(req,res)=>{const p=(await q('SELECT file_path FROM college_proofs WHERE id=$1',[req.params.id])).rows[0];if(!p?.file_path)return res.status(404).json({error:'Proof file not found'});let files=[];try{const parsed=JSON.parse(p.file_path);files=Array.isArray(parsed)?parsed:[parsed]}catch{files=[p.file_path]}const existing=files.map(f=>path.resolve(f)).filter(f=>fs.existsSync(f));if(!existing.length)return res.status(404).json({error:'Proof file is missing from storage. The database record exists, but the uploaded file is no longer present on this server.'});res.sendFile(existing[0])});

r.get('/interns',async(req,res)=>res.json((await q(`SELECT ip.*,u.email,u.status account_status,u.is_active,c.name college_name,b.id batch_id,b.name batch_name,ba.id allocation_id,d.name final_domain FROM intern_profiles ip JOIN users u ON u.id=ip.user_id LEFT JOIN colleges c ON c.id=ip.college_id LEFT JOIN batch_allocations ba ON ba.intern_id=ip.id LEFT JOIN batches b ON b.id=ba.batch_id LEFT JOIN domains d ON d.id=ip.final_domain_id ORDER BY ip.created_at DESC`)).rows));
r.get('/mentors',async(req,res)=>res.json((await q(`SELECT m.*,u.email FROM mentors m JOIN users u ON u.id=m.user_id WHERE m.active ORDER BY m.full_name`)).rows));
r.post('/questions',async(req,res)=>{const b=req.body;const x=(await q(`INSERT INTO question_bank(domain_id,topic,difficulty,type,question,options,correct_answer,marking_guide,marks,explanation,status,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'ACTIVE',$11) RETURNING *`,[b.domainId||null,b.topic,b.difficulty||'MEDIUM',b.type||'TEXT',b.question,b.options||null,b.correctAnswer||null,b.markingGuide||null,b.marks||1,b.explanation||null,b.source||'MANUAL'])).rows[0];res.status(201).json(x)});
r.post('/assessments',async(req,res)=>{const b=req.body;const x=(await q(`INSERT INTO assessments(batch_id,name,window_start,window_end,duration_minutes,attempt_count,randomize,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[b.batchId,b.name,b.windowStart||null,b.windowEnd||null,b.durationMinutes||60,b.attemptCount||1,b.randomize!==false,b.status||'PUBLISHED'])).rows[0];if(b.questionIds?.length)await q('INSERT INTO assessment_sections(assessment_id,name,pass_score,question_ids) VALUES($1,$2,$3,$4)',[x.id,'Common / Domain Assessment',b.passScore||50,b.questionIds]);res.status(201).json(x)});
r.post('/groups',async(req,res)=>{const b=req.body;const g=(await q("INSERT INTO groups(batch_id,name,type,status) VALUES($1,$2,$3,'SYSTEM_DRAFT') RETURNING *",[b.batchId,b.name,b.type||'SINGLE_DOMAIN'])).rows[0];for(const internId of b.internIds||[])await q('INSERT INTO group_members(group_id,intern_id,domain_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[g.id,internId,b.domainId||null]);res.status(201).json(g)});
r.post('/mentor-assignments',async(req,res)=>{const b=req.body;const x=(await q('INSERT INTO mentor_assignments(mentor_id,group_id,domain_id,is_lead) VALUES($1,$2,$3,$4) RETURNING *',[b.mentorId,b.groupId,b.domainId||null,b.isLead!==false])).rows[0];if(x.is_lead)await q('UPDATE groups SET lead_mentor_id=$1 WHERE id=$2',[b.mentorId,b.groupId]);res.status(201).json(x)});
r.post('/projects',async(req,res)=>{const b=req.body;res.status(201).json((await q('INSERT INTO projects(title,description,domain_ids,milestones,tools_methods,resources,duration_suitability,deliverable_types) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[b.title,b.description||null,b.domainIds||[],b.milestones||[],b.toolsMethods||null,b.resources||null,b.durationSuitability||null,b.deliverableTypes||[]])).rows[0])});
r.post('/project-assignments',async(req,res)=>{const b=req.body;res.status(201).json((await q('INSERT INTO project_assignments(project_id,group_id,assigned_by) VALUES($1,$2,$3) ON CONFLICT(project_id,group_id) DO UPDATE SET status=\'ASSIGNED\' RETURNING *',[b.projectId,b.groupId,req.user.id])).rows[0])});
r.post('/tasks',async(req,res)=>{const b=req.body;res.status(201).json((await q('INSERT INTO weekly_tasks(batch_id,domain_id,group_id,title,description,expected_output,submission_types,resources,release_at,due_at,marks,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *',[b.batchId,b.domainId||null,b.groupId||null,b.title,b.description||null,b.expectedOutput||null,b.submissionTypes||[],b.resources||null,b.releaseAt||null,b.dueAt||null,b.marks||100,b.status||'RELEASED'])).rows[0])});
r.get('/reviews',async(req,res)=>res.json((await q(`SELECT fr.*,g.name group_name FROM fortnight_reviews fr JOIN groups g ON g.id=fr.group_id ORDER BY fr.review_date DESC`)).rows));
r.get('/completions',async(req,res)=>res.json((await q(`SELECT ip.id intern_id,ip.full_name,d.name domain_name,fe.group_marks,fe.individual_marks,fe.mentor_feedback,ca.status completion_status,ca.reason,c.certificate_id,c.status certificate_status FROM intern_profiles ip LEFT JOIN domains d ON d.id=ip.final_domain_id LEFT JOIN LATERAL (SELECT * FROM final_evaluations x WHERE x.intern_id=ip.id ORDER BY x.created_at DESC LIMIT 1) fe ON true LEFT JOIN LATERAL (SELECT * FROM completion_approvals x WHERE x.intern_id=ip.id ORDER BY x.approved_at DESC LIMIT 1) ca ON true LEFT JOIN certificates c ON c.intern_id=ip.id ORDER BY ip.full_name`)).rows));
r.post('/completions/:internId/decision',async(req,res)=>{const {status,reason}=req.body;if(!['APPROVED','REJECTED'].includes(status))return res.status(400).json({error:'Invalid completion decision'});const x=(await q('INSERT INTO completion_approvals(intern_id,status,reason,approved_by) VALUES($1,$2,$3,$4) RETURNING *',[req.params.internId,status,reason||null,req.user.id])).rows[0];await audit(req,'COMPLETION_'+status,'intern',req.params.internId,null,x);res.status(201).json(x)});
r.post('/certificates/:internId/issue',async(req,res)=>{const ok=(await q("SELECT 1 FROM completion_approvals WHERE intern_id=$1 AND status='APPROVED' ORDER BY approved_at DESC LIMIT 1",[req.params.internId])).rowCount;if(!ok)return res.status(409).json({error:'Completion approval required'});const p=(await q('SELECT ip.*,d.name domain_name FROM intern_profiles ip LEFT JOIN domains d ON d.id=ip.final_domain_id WHERE ip.id=$1',[req.params.internId])).rows[0];const certId='GAINT-CERT-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,10).toUpperCase();const x=(await q(`INSERT INTO certificates(intern_id,mode,status,certificate_id,issue_date,domain_snapshot,date_snapshot) VALUES($1,$2,'ISSUED',$3,current_date,$4,$5) ON CONFLICT(certificate_id) DO NOTHING RETURNING *`,[p.id,req.body.mode||'IN_APP',certId,p.domain_name||'',req.body.dateSnapshot||''])).rows[0];res.status(201).json(x)});
r.get('/audit',async(req,res)=>res.json((await q('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 500')).rows)); export default r;
