"use client";
import {useEffect,useState} from 'react';import {api} from '../../lib/api';
export default function Page(){const [d,setD]=useState(null),[msg,setMsg]=useState(''),[err,setErr]=useState('');
const load=()=>api('/mentor/dashboard').then(setD).catch(e=>setErr(e.message));useEffect(()=>{load()},[]);
async function evaluate(s){const marks=prompt('Marks:');if(marks===null)return;const feedback=prompt('Feedback:')||'';try{await api('/mentor/submissions/'+s.id+'/evaluate',{method:'POST',body:JSON.stringify({marks:Number(marks),feedback,status:'APPROVED'})});setMsg('Task evaluation saved successfully.');load()}catch(e){setErr(e.message)}}
async function review(g){const periodNo=prompt('Review period number:');if(!periodNo)return;const groupMarks=prompt('Group marks:');if(groupMarks===null)return;const feedback=prompt('Review feedback:')||'';try{await api('/mentor/reviews',{method:'POST',body:JSON.stringify({groupId:g.id,periodNo:Number(periodNo),reviewDate:new Date().toISOString().slice(0,10),status:'PUBLISHED',progress:'Reviewed',domainReview:'Reviewed',presentationReview:'Reviewed',groupMarks:Number(groupMarks),feedback,actionItems:'',nextExpectations:''})});setMsg('Fortnight review published successfully.');load()}catch(e){setErr(e.message)}}
async function finalEval(g){try{const members=await api('/mentor/groups/'+g.id+'/members');if(!members.length)throw new Error('No active members in this group.');const names=members.map((m,i)=>(i+1)+'. '+m.full_name).join('\n');const pick=Number(prompt('Choose intern number:\n'+names))-1;if(!members[pick])return;const groupMarks=Number(prompt('Group marks:'));const individualMarks=Number(prompt('Individual marks:'));const mentorFeedback=prompt('Final feedback:')||'';const recommendation=prompt('Recommendation (COMPLETED / NEEDS_WORK):')||'COMPLETED';await api('/mentor/final-evaluations',{method:'POST',body:JSON.stringify({groupId:g.id,internId:members[pick].id,groupMarks,individualMarks,mentorFeedback,recommendation})});setMsg('Final evaluation submitted for Admin completion approval.')}catch(e){setErr(e.message)}}
if(!d)return <main className="wrap">{err?<p className="error">{err}</p>:<p>Loading mentor workspace…</p>}</main>;
return <main className="wrap"><h1>Mentor Dashboard</h1><p className="muted">Manage assigned groups, evaluate weekly work, publish fortnight reviews and submit final evaluations.</p>{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}
<div className="intern-sections"><section className="card"><h2>Assigned Groups</h2>{!d.groups.length?<p className="muted">No groups assigned.</p>:d.groups.map(g=><div className="workflow-row" key={g.id}><div><b>{g.name}</b><div className="muted">{g.status}</div></div><div><button className="btn" onClick={()=>review(g)}>Fortnight Review</button> <button className="btn secondary" onClick={()=>finalEval(g)}>Final Evaluation</button></div></div>)}</section>
<section className="card"><h2>Pending Task Evaluations</h2>{!d.submissions.length?<p className="muted">No submissions awaiting evaluation.</p>:d.submissions.map(s=><div className="workflow-row" key={s.id}><div><b>{s.title}</b><div>{s.full_name}</div></div><button className="btn" onClick={()=>evaluate(s)}>Evaluate</button></div>)}</section></div></main>}